update

diff --git a/frpo/frpo-1metascan b/frpo/frpo-1metascan
--- a/frpo/frpo-1metascan
+++ b/frpo/frpo-1metascan
@@ -26,28 +26,27 @@ log_msg () { echo "($cmd_name) $@" >&2; }
 
 export LC_ALL=C TMPDIR=/dev/shm
 if (( $# )); then
-   for dir in "$@"; do
-      [[ -d "$dir" ]] || {
-         log_msg "Error: directory '$dir' wrong or unreachable"
-         err=1
-      }
-   done
-   if (( err )); then
-      log_msg 'Execution aborted'
-      exit
-   else
-      log_msg 'Directory arguments check passed'
-   fi
-   path_f=p
+    for dir in "$@"; do
+        [[ -d "$dir" ]] || {
+            log_msg "Error: directory '$dir' wrong or unreachable"
+            err=1
+        }
+    done
+    if (( err )); then
+        log_msg 'Execution aborted'
+        exit
+    else
+        log_msg 'Directory arguments check passed'
+    fi
+    path_f=p
 else
-   path_f=P # %P avoids a leading './' on output when using find without file system arguments
+    path_f=P # %P avoids a leading './' on output when using find without file system arguments
 fi
 
 warn_p=$(log_msg 'Warning: ' 2>&1)
 warn_s=" '%$path_f' skipped as name includes one of the reserved chars \\\n\\\t\\\a\n"
 
 find "$@" \! -empty \( -name '*['$'\n\t\a'']*' \
-   \( -type f -fprintf /dev/stderr "$warn_p"file"$warn_s" -o \
-      -type d -fprintf /dev/stderr "$warn_p"directory"$warn_s" -prune \) -o \
-   -type f \! -iname desktop.ini \! -iname thumbs.db -printf "%TY%Tm%Td-%TH%TM\t%s\t%$path_f\n" \)
-
+    \( -type f -fprintf /dev/stderr "$warn_p"file"$warn_s" -o \
+        -type d -fprintf /dev/stderr "$warn_p"directory"$warn_s" -prune \) -o \
+    -type f \! -iname desktop.ini \! -iname thumbs.db -printf "%TY%Tm%Td-%TH%TM\t%s\t%$path_f\n" \)
diff --git a/frpo/frpo-3sync b/frpo/frpo-3sync
--- a/frpo/frpo-3sync
+++ b/frpo/frpo-3sync
@@ -3,90 +3,135 @@
 help () {
 cat >&2 <<EOF
 FRPO - File Recovery Priority Organizer
-bad to safe storage file recovery synchronization based on metadata lists
+3-phase file recovery syncing based on metadata lists
 
-Usage:  ${0##*/} [-hqv] SOURCE_BASE_DIR DEST_BASE_DIR METADATA_LIST [...]
+Usage:  ${0##*/} [-12fvqh] SOURCE_BASE_DIR DEST_BASE_DIR METADATA_LIST [...]
 
-Options
+By default recovery starts using rsync mode(0), being fast with simple retries
+to easily skip (purposely) difficult files, if this phase ends with errors
+recovery of incomplete files is restarted using ddrescue tool (mode1/2).
+
+Start recovery mode and phase options:
+-1	ddrescue optimal mode(1): block level copy, good speed
+-2	ddrescue deep mode(2): block level copy, max effort, slow, stressful
+-f	do not switch into deeper modes after phase ending with errors/skips
+
+Other options:
+-v	(rsync) print file transfer progress and speed
+-q	(rsync) quiet operation, print only errors
 -h	print this help screen
--q	quiet operation, print only errors
--v	print file transfer progress and speed
 EOF
 exit
 }
 
+(( $# )) || help
 export LC_ALL=C TMPDIR=/dev/shm
 IFS=$'\n'
-verbose=-i
-[[ $1 = -* ]] && {
-   case "${1:1}" in
-      h) help ;;
-      q) verbose= ;;
-      v) verbose+=P ;;
-      *) echo "Unknown option '$1'"; exit ;;
-   esac
-   shift
-}
-(( $# < 3 )) && help
+mode=0
+verbose=i
 
+. sk-args-canon
+while [[ $1 = -* ]]; do
+    case "${1:1}" in
+        1|2) mode=${1:1} ;;
+        f) f_mode=1 ;;
+        v) verbose=iP ;;
+        q) verbose= ;;
+        h) help ;;
+        *) echo "Error: unknown option '$1'"; exit 1 ;;
+    esac
+    shift
+done
+(( $# < 3 )) && {
+    echo -e 'Error: at least 3 arguments needed\n'
+    exit 1
+}
+
+modes=(rsync ddrescue-optimal ddrescue-deep)
 source=$1
 dest=$2
-ddrescue_cmd () { ddrescue -pb4096 "$@" -- "$source/$f_name" "$r_path"-{img,map}; }
+ddrescue_cmd () {
+    local dir=${f_path%/*}
+    [[ -d "$dir" ]] || mkdir -p -- "$dir"
+    ddrescue -p "$@" -- "$source/$r_path" "$ddr_path"{img,map}
+}
 
-for meta_l in "${@:3}"; do
-   let err_c=0
-   # Read relative path names and copy them one by one
-   while read -r f_name; do
-      r_path=$dest/$f_name.ddr
-      # Detect if have to continue a previous incomplete ddrescue recovery
-      if [[ -f $r_path-img ]]; then
-         ddr=2
-      else
-         # Rsync options:
-         # --append even if desirable is not used as from test results with damaged sources can fake
-         # complete file copy by padding with zeroes or garbage from read errors!
-         # --inplace is better than --partial alone as will overwrite previous copy (attempt), so at worst
-         # the resulting file size will be the same as before.
-         # In the end none of these options have been used as rsync tends to leave invalid copies as valid
-         rsync -Rt $verbose "$source/./$f_name" "$dest"
-         err=$?
-         # Check if rsync fails
-         if (( err )); then
-            # Detect rsync break signal by user and exit after printing stats
-            (( err == 20 )) && exit
-            # Any other error is considered rsync failing, so enable ddrescue mode for this file
-            ddr=1
-            let err_c++
-         else
-            continue
-         fi
-      fi
-      # If here, ddrescue method kicks in, this creates and maintains a map file for each file to
-      # to perform a smart stepwise recovery (can be interrupted/continued anytime), until completion
-      (( ddr == 1 )) && {
-         # As first recovery attempt use a trivial setting to fastly get easily readable parts
-         ddrescue_cmd -n
-         # If ddrescue recovery hasn't finished all parts set for serious mode (ddr=2)
-         ddrescuelog -D "$r_path"-map && ddr=0 || ddr=2
-      }
-      (( ddr == 2 )) && {
-         # 2nd pass uses the tipical and (time) demanding ddrescue setup to recover troublesome areas
-         ddrescue_cmd -dr3
-         ddrescuelog -D "$r_path"-map && ddr=0
-      }
-      if (( ddr )); then
-         let err_c++
-      else
-         mv -- "$r_path"-img "$dest/$f_name"
-         touch -r {"$source","$dest"}/"$f_name"
-         rm -- "$r_path"-map
-      fi
-   done < <(cut -f3 "$meta_l")
-
-   echo -e "\n'$meta_l' done, errors count: $err_c"
-   (( err_c )) && {
-      echo 'Waiting 5sec before proceeding with next list (press CTRL-C if you want to break)'
-      sleep 5 || exit
-   }
+while :; do
+    all_rec_c=0
+    all_skip_c=0
+    all_err_c=0
+    for meta_l in "${@:3}"; do
+        rec_c=0
+        skip_c=0
+        err_c=0
+        # Read relative path names and copy them one by one
+        while read -r r_path; do
+            # Final full destination path
+            f_path=$dest/$r_path
+            [[ -f "$f_path" ]] && continue
+            ddr_path=$f_path.ddr-
+            
+            if (( mode )); then
+                # ddrescue modes create and maintain a map file for each file to perform a smart stepwise
+                # block level recovery that can be interrupted/continued without losing progress
+                if (( mode == 1 )); then
+                    # Mode1 (optimal): good compromise setting to easily get readable parts
+                    ddrescue_cmd -n
+                else
+                    # Mode2 (deep): maximum effort to try to recover troublesome areas
+                    ddrescue_cmd -dr3
+                fi
+                if ddrescuelog -D "$ddr_path"map; then
+                    # ddrescue full recovery done
+                    # Rename image file to original file name, restore date, delete map file
+                    mv -- "$ddr_path"img "$f_path"
+                    touch -r "$source/$r_path" -- "$f_path"
+                    rm -- "$ddr_path"map
+                    let rec_c++
+                else
+                    # Increase error count as ddrescue hasn't recovered all parts yet
+                    let err_c++
+                fi
+            else
+                # Mode0 uses rsync
+                # If the file is found in a (previous) incomplete ddrescue state skip it
+                [[ -f "$ddr_path"img ]] && {
+                    let skip_c++
+                    continue
+                }
+                # Rsync options:
+                # --append even if desirable is not used as from test results with damaged sources
+                # can fake complete file copy by padding with zeroes or garbage from read errors!
+                # --inplace is better than --partial alone as will overwrite previous copy (attempt),
+                # so at worst the resulting file size will be the same as before.
+                # In the end none of these options have been used as rsync tends to leave invalid copies
+                rsync -Rt$verbose "$source/./$r_path" "$dest"
+                # Check rsync exit status
+                case $? in
+                    0) let rec_c++ ;;
+                    # Detect rsync break signal by user and exit after printing stats
+                    20) exit ;;
+                    # Any other error is considered rsync failing, so increase error count
+                    *) let err_c++ ;;
+                esac
+            fi
+        done < <(cut -f3 "$meta_l")
+        
+        let all_rec_c+=rec_c
+        let all_skip_c+=skip_c
+        let all_err_c+=err_c
+        echo -e "\nList '$meta_l' done"\
+            "\nRecovered: $rec_c\n  Skipped: $skip_c\n   Failed: $err_c\n"
+        (( err_c+skip_c )) && {
+            echo 'Waiting 5sec before proceeding with next list (press CTRL-C if you want to break)'
+            sleep 5 || exit
+        }
+    done
+    
+    echo -e "Mode $mode phase done (${modes[$mode]})" \
+        "\nRecovered: $all_rec_c\n  Skipped: $all_skip_c\n   Failed: $all_err_c\n"
+    (( mode > 1 )) || (( f_mode )) || ! (( all_err_c+all_skip_c )) && break
+    sleep 5
+    let mode++
 done
 
diff --git a/sk-args-to-vars b/sk-args-to-vars
--- a/sk-args-to-vars
+++ b/sk-args-to-vars
@@ -37,20 +37,20 @@ cmd_name=${0##*/}
 
 # Gather supported options list, guess variables names, empty variables when not forbidden (+)
 until [[ $1 = -- ]]; do
-   case $1 in
-      '') echo "Error ($cmd_name): Missing parsing line delimiter '--'" >&2; set --; break ;;
-      -*) echo "Error ($cmd_name): Unknown option '$1'" >&2; set --; break ;;
-      *)
-         i=${1%%[.=]*}
-         if (( ${#i} > 1 )); then
-            i=${i//-/_}
-         else
-            i=_"$i"_
-         fi
-         o+="$i.$1 "
-      ;;
-   esac
-   shift
+    case $1 in
+        '') echo "Error ($cmd_name): Missing parsing line delimiter '--'" >&2; set --; break ;;
+        -*) echo "Error ($cmd_name): Unknown option '$1'" >&2; set --; break ;;
+        *)
+            i=${1%%[.=]*}
+            if (( ${#i} > 1 )); then
+                i=${i//-/_}
+            else
+                i=_"$i"_
+            fi
+            o+="$i.$1 "
+        ;;
+    esac
+    shift
 done
 shift
 
@@ -58,60 +58,59 @@ shift
 # on 1st extraneous option, isolated argument or -- set parsed args number to "parsed_argc" and exit
 declare -i parsed_argc=$#
 while (( $# )); do
-   case $1 in
-      -[^-]*)
-         for (( i=1; i < ${#1}; i++ )); do
-            c=${1:$i:1}
+    case $1 in
+        -[^-]*)
+            for (( i=1; i < ${#1}; i++ )); do
+                c=${1:$i:1}
+                l=${o%.$c[.= ]*}
+                # tricky way to seek in the options template "o" the right one without external tools
+                if [[ $l != $o ]]; then
+                    r=${o#$l}
+                    j=${l##* }${r%% *}
+                    # option type: PARAMETER or FLAG ?
+                    if [[ ${j: -1} = = ]]; then
+                        # assignment and value joint in same argument?
+                        if (( $i < ${#1}-1 )); then
+                            eval ${j%%.*}='${1:$i+1}'
+                        else
+                            eval ${j%%.*}='$2'
+                            shift
+                        fi
+                        break
+                    else
+                        let ${j%%.*}++
+                    fi
+                else
+                    break 2
+                fi
+            done ;;
+        --) shift; break ;;
+        --[^-]*)
+            i=${1:2}
+            # if "=" doesn't match "c" and "i" will be equal
+            c=${i%%=*}
             l=${o%.$c[.= ]*}
-            # tricky way to seek in the options template "o" the right one without external tools
             if [[ $l != $o ]]; then
-               r=${o#$l}
-               j=${l##* }${r%% *}
-               # option type: PARAMETER or FLAG ?
-               if [[ ${j: -1} = = ]]; then
-                  # assignment and value joint in same argument?
-                  if (( $i < ${#1}-1 )); then
-                     eval ${j%%.*}='${1:$i+1}'
-                  else
-                     eval ${j%%.*}='$2'
-                     shift
-                  fi
-                  break
-               else
-                  let ${j%%.*}++
-               fi
+                r=${o#$l}
+                j=${l##* }${r%% *}
+                # option type: PARAMETER or FLAG ?
+                if [[ ${j: -1} = = ]]; then
+                    if [[ $c != $i ]]; then
+                        eval ${j%%.*}='${i#$c=}'
+                    else
+                        eval ${j%%.*}=
+                    fi
+                else
+                    let ${j%%.*}++
+                fi
             else
-               break 2
+                break
             fi
-         done ;;
-      --) shift; break ;;
-      --[^-]*)
-         i=${1:2}
-         # if "=" doesn't match "c" and "i" will be equal
-         c=${i%%=*}
-         l=${o%.$c[.= ]*}
-         if [[ $l != $o ]]; then
-            r=${o#$l}
-            j=${l##* }${r%% *}
-            # option type: PARAMETER or FLAG ?
-            if [[ ${j: -1} = = ]]; then
-               if [[ $c != $i ]]; then
-                  eval ${j%%.*}='${i#$c=}'
-               else
-                  eval ${j%%.*}=
-               fi
-            else
-               let ${j%%.*}++
-            fi
-         else
-            break
-         fi
-      ;;
-      *) break ;;
-   esac
-   shift
+        ;;
+        *) break ;;
+    esac
+    shift
 done
 let parsed_argc-=$#
 
 unset i j c l r o
-
diff --git a/sk-backup-vm b/sk-backup-vm
--- a/sk-backup-vm
+++ b/sk-backup-vm
@@ -10,8 +10,8 @@ EOF
 exit
 }
 error_exit () {
-   printf %s\\n "$cmd_name: Error, $@"
-   exit 1
+    printf %s\\n "$cmd_name: Error, $@"
+    exit 1
 }
 (( $(id -u) )) && error_exit "must be root"
 
@@ -23,9 +23,9 @@ borg_cmd=(borg create --read-special "${@:1:$#-1}")
 export TMPDIR=/dev/shm LC_ALL=C
 tmp=$(mktemp -d) || exit
 trap '
-   pkill -P $$
-   [[ -n $tmp ]] && { cd ..; rm -- $tmp/*; rmdir -- $tmp; }
-   [[ -n $bdev ]] && losetup -d $bdev
+    pkill -P $$
+    [[ -n $tmp ]] && { cd ..; rm -- $tmp/*; rmdir -- $tmp; }
+    [[ -n $bdev ]] && losetup -d $bdev
 ' EXIT
 cd $tmp || exit
 
@@ -33,35 +33,34 @@ cd $tmp || exit
 sfdisk -d "$img" > dump.sfdisk
 pttype=$(blkid -o value -s PTTYPE $bdev)
 if [[ $pttype =~ ^(dos|gpt)$ ]]; then
-   head -c512 $bdev > mbr
+    head -c512 $bdev > mbr
 else
-   pttype=
+    pttype=
 fi
 
 plist=($bdev?*)
 if [[ -n $plist ]]; then
-   for part in ${plist[@]}; do
-      # Using "blkid" as "lsblk" shows a (no output) bug when closely invoked 2 times
-      fs=$(blkid -o value -s TYPE $part)
-      case $fs in
-         vfat)
-            a=$(file -bs $part | sed 's/.*FAT (\([0-9]\{2\}\) bit).*/\1/')
-            [[ $a =~ ^(12|16|32|64)$ ]] && fs=fat$a
-         ;&
-         exfat) read_cmd=(partclone.$fs -qcs $part) ;;
-         ntfs) read_cmd=(ntfsclone -qso - $part) ;;
-         ?*) fs+=. ;&
-         *) fs+=raw; read_cmd=(cat $part) ;;
-      esac
-      pfile=${part:${#bdev}}.$fs
-      # Named pipes do the trick to serve backup input from stream sources
-      mkfifo -m0600 $pfile
-      ${read_cmd[@]} > $pfile &
-   done
+    for part in ${plist[@]}; do
+        # Using "blkid" as "lsblk" shows a (no output) bug when closely invoked 2 times
+        fs=$(blkid -o value -s TYPE $part)
+        case $fs in
+            vfat)
+                a=$(file -bs $part | sed 's/.*FAT (\([0-9]\{2\}\) bit).*/\1/')
+                [[ $a =~ ^(12|16|32|64)$ ]] && fs=fat$a
+            ;&
+            exfat) read_cmd=(partclone.$fs -qcs $part) ;;
+            ntfs) read_cmd=(ntfsclone -qso - $part) ;;
+            ?*) fs+=. ;&
+            *) fs+=raw; read_cmd=(cat $part) ;;
+        esac
+        pfile=${part:${#bdev}}.$fs
+        # Named pipes do the trick to serve backup input from stream sources
+        mkfifo -m0600 $pfile
+        ${read_cmd[@]} > $pfile &
+    done
 elif [[ -z $pttype ]]; then
-   # Get the whole image only when no partitions are detected and with uncommon layouts
-   mkfifo -m0600 image.raw
-   cat $bdev > image.raw &
+    # Get the whole image only when no partitions are detected and with uncommon layouts
+    mkfifo -m0600 image.raw
+    cat $bdev > image.raw &
 fi
 "${borg_cmd[@]}" *
-
diff --git a/sk-borg-prune b/sk-borg-prune
--- a/sk-borg-prune
+++ b/sk-borg-prune
@@ -4,7 +4,7 @@ help () {
 cat >&2 <<EOF
 $cmd_name -- Borg backup archive pruning wrapper
 
-Syntax:  $cmd_name [options] REPO ARCHIVE
+Syntax:  $cmd_name [OPTIONS] REPO ARCHIVE
 
 Wrapper options:
 -n --keep=NUM	Maximum number of archives to keep and rotate
@@ -36,26 +36,26 @@ args_par=ntE
 . sk-args-canon
 
 while [[ $1 = -* ]]; do
-   case "${1:1}" in
-      n|keep=) keep=$2; shift ;;
-      t|time=) time=$(sk-time-to-sec "$2"); shift ;;
-      E|exp=) exp=$2; shift ;;
-      h|help) help ;;
-      p|progress) b_opt+=(-p) ;;
-      list) b_opt+=(--list) ;;
-      s|stats) b_opt+=(-s) ;;
-      *) log_msg "Error: unknown option '$1'"; exit 1 ;;
-   esac
-   shift
+    case "${1:1}" in
+        n|keep=) keep=$2; shift ;;
+        t|time=) time=$(sk-time-to-sec "$2"); shift ;;
+        E|exp=) exp=$2; shift ;;
+        h|help) help ;;
+        p|progress) b_opt+=(-p) ;;
+        list) b_opt+=(--list) ;;
+        s|stats) b_opt+=(-s) ;;
+        *) log_msg "Error: unknown option '$1'"; exit 1 ;;
+    esac
+    shift
 done
 (( $# != 2 )) && {
-   log_msg 'Error: must specify repository and archive prefix'
-   exit 1
+    log_msg 'Error: must specify repository and archive prefix'
+    exit 1
 }
 
 repo=$1
 arch=$2
 rm_list=($(borg list --short -a "$arch-[0-9][0-9][0-9][0-9]*" "$repo" | \
-   keep=$keep time=$time exp=$exp sk-prune-dates))
+    keep=$keep time=$time exp=$exp sk-prune-dates))
 
 (( ${#rm_list[@]} )) && borg delete ${b_opt[@]} "$repo" "${rm_list[@]}"
diff --git a/sk-rdp-ssh b/sk-rdp-ssh
--- a/sk-rdp-ssh
+++ b/sk-rdp-ssh
@@ -6,41 +6,40 @@ RDP tunnelling through SSH
 
 Syntax:  ${0##*/} [-p PORT] USER@SSH_SERVER[:PORT] [xfreerdp options] RDP_SERVER
 EOF
-   exit
+    exit
 }
 
 # Setup SSH client arguments
 while [[ $1 != *?@?* ]]; do
-   (( $# )) || {
-      echo "Error: missing gateway address"
-      exit
-   }
-   ssh_args+=("$1")
-   shift
+    (( $# )) || {
+        echo "Error: missing gateway address"
+        exit
+    }
+    ssh_args+=("$1")
+    shift
 done
 # Remote address can be indicated in compact (addr@user:port) or standard format (-p port addr@user)
 if [[ $1 = *?:[0-9]* ]]; then
-   ssh_args+=("-p${1#*:}" "${1%:*}")
+    ssh_args+=("-p${1#*:}" "${1%:*}")
 else
-   ssh_args+=("$1")
+    ssh_args+=("$1")
 fi
 shift
 
 # Setup RDP client arguments
 rdp_server_p=3389
 case "${@: -1}" in
-   [[:alnum:]]*:[0-9]*)	rdp_server=${@: -1}; i=$#-1;;			# specific server : specific port
-   [[:alnum:]]*)	rdp_server=${@: -1}:$rdp_server_p; i=$#-1;;	# specific server : default port
-   :[0-9]*)		rdp_server=127.0.0.1${@: -1}; i=$#-1;;		# server loopback : specific port
-   *)			rdp_server=127.0.0.1:$rdp_server_p; i=$#;;	# server loopback : default port
+    [[:alnum:]]*:[0-9]*)	rdp_server=${@: -1}; i=$#-1;;			# specific server : specific port
+    [[:alnum:]]*)	rdp_server=${@: -1}:$rdp_server_p; i=$#-1;;	# specific server : default port
+    :[0-9]*)		rdp_server=127.0.0.1${@: -1}; i=$#-1;;		# server loopback : specific port
+    *)			rdp_server=127.0.0.1:$rdp_server_p; i=$#;;	# server loopback : default port
 esac
 
 gw_name=$(sk-ssh "${ssh_args[@]}" "echo \$HOSTNAME") && \
 rdp_client_p=$(python -c 'import socket; s=socket.socket(); s.bind(("", 0)); print(s.getsockname()[1]); s.close()') && \
 sk-ssh -fL localhost:$rdp_client_p:$rdp_server "${ssh_args[@]}" "sleep 3" && \
 xfreerdp \
-   +z /cert-ignore -encryption \
-   +fonts -aero -window-drag -menu-anims -themes -wallpaper \
-   /bpp:16 /size:1280x960 "${@:1:$i}" /v:127.0.0.1:$rdp_client_p \
-   /t:"${ssh_args[@]: -1}  ($gw_name)  -  ${rdp_server%:$rdp_server_p}"
-
+    +z /cert-ignore -encryption \
+    +fonts -aero -window-drag -menu-anims -themes -wallpaper \
+    /bpp:16 /size:1280x960 "${@:1:$i}" /v:127.0.0.1:$rdp_client_p \
+    /t:"${ssh_args[@]: -1}  ($gw_name)  -  ${rdp_server%:$rdp_server_p}"
diff --git a/sk-vnc-ssh b/sk-vnc-ssh
--- a/sk-vnc-ssh
+++ b/sk-vnc-ssh
@@ -8,21 +8,20 @@ unset ssvnc
 declare -i i=1
 
 while :; do
-   if (( $i > $# )); then
-      echo "Error: missing gateway address"
-      exit 1
-   elif [[ "${@:$i:1}" = *?@?* ]]; then
-      case "${@: -1}" in
-         -)		host=127.0.0.1:$vnc_port ;;	# server loopback : default port
-         :[0-9]*)	host=127.0.0.1${@: -1} ;;	# server loopback : specific port
-         *?:[0-9]*)	host=${@: -1} ;;		# specific server : specific port
-         *)		host=${@: -1}:$vnc_port ;;	# specific server : default port
-      esac
-      ssh=${@:1:$i}
-      ssvnc=("${@:$i+1:$#-$i-1}")
-      ssvncviewer exec="sk-ssh -W $host $ssh" -enc zrle -bgr233 "${ssvnc[@]}"
-      exit
-   fi
-   let i++
+    if (( $i > $# )); then
+        echo "Error: missing gateway address"
+        exit 1
+    elif [[ "${@:$i:1}" = *?@?* ]]; then
+        case "${@: -1}" in
+            -)		host=127.0.0.1:$vnc_port ;;	# server loopback : default port
+            :[0-9]*)	host=127.0.0.1${@: -1} ;;	# server loopback : specific port
+            *?:[0-9]*)	host=${@: -1} ;;		# specific server : specific port
+            *)		host=${@: -1}:$vnc_port ;;	# specific server : default port
+        esac
+        ssh=${@:1:$i}
+        ssvnc=("${@:$i+1:$#-$i-1}")
+        ssvncviewer exec="sk-ssh -W $host $ssh" -enc zrle -bgr233 "${ssvnc[@]}"
+        exit
+    fi
+    let i++
 done
-
